spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 991013114702-onqp7vli1s3jhej98vfvcqmp8kjm2gdd.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          naver:
            client-id: 8rMRGOBFggad21EPNAoS
            client-secret: txl3lJooF8
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver
          kakao:
            clientId: b51a87369fa2be0b6083d66f1c49470e
            clientSecret: 67vWfW0TplCBct9VVCW5YwSnhIzIFsOF
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirectUri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - account_email
            clientName: Kakao
          # Provider 설정
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

# cors 설정
cors:
  allowed-origins: 'http://localhost:8080'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080/oauth/redirect


jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot